-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 11:09:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rpgnasala
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rpgnasala
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpgnasala` DEFAULT CHARACTER SET utf8 ;
USE `rpgnasala` ;

-- -----------------------------------------------------
-- Table `rpgnasala`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpgnasala`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `xp` INT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgnasala`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpgnasala`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgnasala`.`quest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpgnasala`.`quest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questao` VARCHAR(255) NULL,
  `resposta` VARCHAR(255) NULL,
  `valor` INT NULL,
  `tempoInicio` DATETIME NULL,
  `tempoFim` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgnasala`.`turma_has_quest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpgnasala`.`turma_has_quest` (
  `turma_id` INT NOT NULL,
  `quest_id` INT NOT NULL,
  PRIMARY KEY (`turma_id`, `quest_id`),
  INDEX `fk_turma_has_quest_quest1_idx` (`quest_id` ASC),
  INDEX `fk_turma_has_quest_turma1_idx` (`turma_id` ASC),
  CONSTRAINT `fk_turma_has_quest_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `rpgnasala`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_quest_quest1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `rpgnasala`.`quest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
